### ISSUE TITLE
Players can spawn at the same coordinates.

### ISSUE THREAD

**Issue by Dmitry221060** [tutturu-tv/rush#4]
When a new player connects to a room, the player is placed at random coordinates, regardless of whether the cell is occupied or not.
https://github.com/tutturu-tv/rush/blob/8cf69b556b8148e771db863aa2d40ed4c3001c6f/game.js#L74-L75
https://github.com/tutturu-tv/rush/blob/8cf69b556b8148e771db863aa2d40ed4c3001c6f/game.js#L105-L107

**Comment by Dmitry221060** [comment]
Fixed via 08f4363ee794813a5c3e66291083c498f69beed1

**Comment by jeda** [comment]
(Just as a hint for next time, @Dmitry221060: You can use `Closes/Fixes #<id>` in the commit messages to automatically close issues once committed/merged in - just so things track themselves out automatically.)
